version: "3.8"
services:
  db:
    build: ./db
    image: db
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
  flask-app:
    build: ./flask-app
    image: flask-app
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    depends_on:
      - "db"
  nginx:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - "flask-app"

volumes:
  mydata:
